### ISSUE TITLE
Umlauts

### ISSUE THREAD

**Issue by janis-bauer** [statsmaths/cleanNLP#31]
I am using cleanNLP in the German version and I am wondering if there is any chance to appropriately deal with umlauts, such as ä, ö and ü.

So far, when I am calling the function using _cnlp_annotate("Übermorgen fährt Lisa ins Freibad")_ the word "Übermorgen" is split up in a weird way. Yet, also converting all "Ü"s to "U"s doesn't help as important prepositions such as "über" are not recongnized any more.

Any ideas?

Thanks for your help,
Janis

**Comment by itsSavvas** [comment]
Hi, 
how do use load the german model with java backend? because I get an error that german model cannot be found .....

thanks, 
Savvas

**Comment by taylor-arnold** [comment]
@janis-bauer I cannot replicate the error that you are getting. Are you using the version of
cleanNLP from GitHub and what backend are you using? A complete working example would
be helpful. Here is what I have using the most current version of cleanNLP and on macOS 
(10.12.6).
```
library(cleanNLP)
Sys.setlocale("LC_ALL", "en_GB.UTF-8")
cnlp_init_udpipe("german")
x <- cnlp_annotate("Übermorgen fährt Lisa ins Freibad")
cnlp_get_token(x)
```
```
    id sid tid       word      lemma  upos   pos cid pid s_after
1 doc1   1   1 Übermorgen Übermorgen PROPN    NN   0   1        
2 doc1   1   2      fährt     fahren  VERB VVFIN  11   1        
3 doc1   1   3       Lisa       Lisa PROPN    NE  17   1        
4 doc1   1   4         in         in   ADP  APPR  22   1        
5 doc1   1   5        das        der   DET   ART  25   1        
6 doc1   1   6    Freibad    Freibad  NOUN    NN  29   1      \n
```
I explicitly set the locale above, though it worked fine for me without that. I could see
a "bad" (non-UTF-8) locale causing issues, though, on something like Windows.

**Comment by taylor-arnold** [comment]
@itsSavvas You need to run `cnlp_download_corenlp("de")` to download the German jar files. Have you done that yet? If so, what happens when you run this command:
```
dir(system.file("extdata", package = "cleanNLP"))
```
```
 [1] "cleanNLP-0.1.jar"                       
 [2] "CoreNLP-to-HTML.xsl"                    
 [3] "english-ud-2.0-170801.udpipe"           
 [4] "german-ud-2.0-170801.udpipe"            
 [5] "StanfordCoreNLP-arabic.properties"      
 [6] "StanfordCoreNLP-chinese.properties"     
 [7] "StanfordCoreNLP-english-all.properties" 
 [8] "StanfordCoreNLP-english-fast.properties"
 [9] "StanfordCoreNLP-french.properties"      
[10] "StanfordCoreNLP-german.properties"      
[11] "StanfordCoreNLP-spanish.properties"     
[12] "StanfordCoreNLP.properties"             
```
The output there is what happens if you have all of the models installed, though
you'll only need German to parse German text. Also, and particular reason to use
CoreNLP? I find udpipe and spacy to both be superior in terms of speed and 
accuracy.

**Comment by taylor-arnold** [comment]
I'm closing this issue, assuming it was resolved. If there are other issues, please open a new issue.

**Comment by fkrauer** [comment]
Hi

I have the same Umlaut problem. 

`cnlp_annotate("Ich würde die Mäuse mit Käse füttern", as_strings = TRUE)`

yields:

`[1] "ich"   "w"     "rde"   "die"   "m"     "use"   "mit"   "k"     "se"    "f"    
 "ttern"`

The words are split wherever the Umlaut is, which makes the tools unusable for me.

I work on a windows machine, where the locale cannot be set explicitly to UFT-8. I tried

`cnlp_annotate(enc2utf8("Ich würde die Mäuse mit Käse füttern"), as_strings = TRUE)`

but it doesn't help. Any suggestions?

Fabienne


session Info

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252   
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_1.3.1    cleanNLP_2.3.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.3   assertthat_0.2.1 R6_2.4.0         cli_1.1.0       
 [5] hms_0.4.2        tools_3.5.3      pillar_1.3.1     tibble_2.1.1    
 [9] Rcpp_1.0.1       crayon_1.3.4     utf8_1.1.4       fansi_0.4.0     
[13] pkgconfig_2.0.2  rlang_0.3.4      rJava_0.9-11

**Comment by taylor-arnold** [comment]
I don't have a Windows environment to easily test it, but I think it is still an encoding issue. You may just need to set the local to something else. Does running this (from the R docs for Windows users) give you an error and/or solve the problem: 

    Sys.setlocale("LC_TIME", "German")

**Comment by fkrauer** [comment]
Hi, the problem of incorrect tokenization with Umlaut persists. I think it is an issue of the Windows environment and UTF-8. Changing the locale does not solve the problem. However, it works fine with your coreNLP package, so I have switched to that now. Best, Fabienne

**Comment by janis-bauer** [comment]
I have recently managed to solve the problem. My solution was to explicitly set the encoding argument in my import step (fread / odbc-connection) to "UTF-8". 

There seem to be some strange issues with Windows & R when the text is defined in the editor and is not imported from an external file. 

Best Janis

**Comment by jwijffels** [comment]
Here is my code on an windows machine. You need to make sure you provide text as UTF-8. Example shown below:

```
> x <- "Ich würde die Mäuse mit Käse füttern"
> Encoding(x)
[1] "latin1"
> x <- iconv(x, from = "latin1", to = "UTF-8")
> Encoding(x)
[1] "UTF-8"
> 
> library(udpipe)
> result <- udpipe(x, "german-gsd")
> result
  doc_id paragraph_id sentence_id                             sentence start end term_id token_id   token   lemma upos  xpos                                                     feats
1   doc1            1           1 Ich würde die Mäuse mit Käse füttern     1   3       1        1     Ich     ich PRON  PPER                Case=Nom|Number=Sing|Person=1|PronType=Prs
2   doc1            1           1 Ich würde die Mäuse mit Käse füttern     5   9       2        2   würde  werden  AUX    NN                           Case=Acc|Gender=Fem|Number=Sing
3   doc1            1           1 Ich würde die Mäuse mit Käse füttern    11  13       3        3     die     der  DET   ART Case=Acc|Definite=Def|Gender=Fem|Number=Sing|PronType=Art
4   doc1            1           1 Ich würde die Mäuse mit Käse füttern    15  19       4        4   Mäuse    Maus NOUN    NN                           Case=Acc|Gender=Fem|Number=Sing
5   doc1            1           1 Ich würde die Mäuse mit Käse füttern    21  23       5        5     mit     mit  ADP  APPR                                                      <NA>
6   doc1            1           1 Ich würde die Mäuse mit Käse füttern    25  28       6        6    Käse    Käse NOUN    NN                           Case=Dat|Gender=Fem|Number=Sing
7   doc1            1           1 Ich würde die Mäuse mit Käse füttern    30  36       7        7 füttern füttern VERB VVINF                                              VerbForm=Inf
  head_token_id dep_rel deps            misc
1             7   nsubj <NA>            <NA>
2             7     aux <NA>            <NA>
3             4     det <NA>            <NA>
4             7     obj <NA>            <NA>
5             6    case <NA>            <NA>
6             4    nmod <NA>            <NA>
7             0    root <NA> SpacesAfter=\\n
> 
> library(cleanNLP)
> cnlp_init_udpipe(model_name = "german-gsd", feature_flag = TRUE)
> result <- cnlp_annotate(x)
> cnlp_get_token(result)
    id sid tid    word   lemma upos   pos cid pid s_after case definite gender number person pron_type verb_form
1 doc1   1   1     Ich     ich PRON  PPER   0   1          Nom     <NA>   <NA>   Sing      1       Prs      <NA>
2 doc1   1   2   würde  werden  AUX    NN   4   1          Acc     <NA>    Fem   Sing   <NA>      <NA>      <NA>
3 doc1   1   3     die     der  DET   ART  10   1          Acc      Def    Fem   Sing   <NA>       Art      <NA>
4 doc1   1   4   Mäuse    Maus NOUN    NN  14   1          Acc     <NA>    Fem   Sing   <NA>      <NA>      <NA>
5 doc1   1   5     mit     mit  ADP  APPR  20   1         <NA>     <NA>   <NA>   <NA>   <NA>      <NA>      <NA>
6 doc1   1   6    Käse    Käse NOUN    NN  24   1          Dat     <NA>    Fem   Sing   <NA>      <NA>      <NA>
7 doc1   1   7 füttern füttern VERB VVINF  29   1      \n <NA>     <NA>   <NA>   <NA>   <NA>      <NA>       Inf
```

**Comment by fkrauer** [comment]
@jwijffels yes thanks, it works with udpipe, but I the output yields only POS information, the NER is missing, which is why I'd prefer a solution with the java coreNLP backend. 

I have gone back to using the corenNLP package. The tokenization and the NER seem to work, the only problem I have  is that the Umlauts are displayed incorrectly in the resulting df: 

`initCoreNLP(stanfordlib, type="german")`
`test <- "In Ägypten gibt es süsse Katzen"`
`tokens <- annotateString(iconv(test, "latin1", "UTF-8"))$token`
`tokens`

```
  sentence id    token lemma CharacterOffsetBegin CharacterOffsetEnd   POS      NER Speaker
1        1  1       In    NA                    0                  2  APPR        O      NA
2        1  2 Ã„gypten    NA                    3                 10    NN LOCATION      NA
3        1  3     gibt    NA                   11                 15 VVFIN        O      NA
4        1  4       es    NA                   16                 18  PPER        O      NA
5        1  5   sÃ¼sse    NA                   19                 24  ADJA        O      NA
6        1  6   Katzen    NA                   25                 31    NN        O      NA
```
It is not a big deal as long as the words are recognized correctly, which they seem to. By the way, does anyone know what the "O" class in the NER actually means? Is it OTHER, or is it a token that is not recognized? Thanks

**Comment by jwijffels** [comment]
udpipe does not provide NER, only POS tag PROPN (https://universaldependencies.org/u/pos/all.html#al-u-pos/PROPN). If you want to build your own NER tagger with your own classes, you can use R package [crfsuite](https://cran.r-project.org/web//packages/crfsuite/index.html). O stands for Outside in the IOB NER tagging scheme.
